name: Update GitHub Stats

on:
  #schedule:
  #  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch GitHub Stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -o github-stats.svg "https://github-readme-stats.vercel.app/api?username=layer07&show_icons=true&count_private=true&theme=radical&include_all_commits=true&custom_title=My+GitHub+Stats&token=${GH_TOKEN}"

      - name: Update README with New Stats
        run: |
          sed -i '/<!-- GITHUB-STATS -->/ {n;d;}; /<!-- GITHUB-STATS -->/ a\
          ![GitHub Stats](./github-stats.svg)' README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md github-stats.svg
          git commit -m "Update GitHub Stats via GitHub Actions" || echo "No changes to commit"
          git push
